## Exercise 1: NumPy: Create an array with values ranging from 12 to 38

In [7]:
a = np.arange(12,38)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
b=np.pad(a,1,'constant',constant_values=(0))
b

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

## Exercise 3: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [19]:
lst=[1,2,3,4,5,6,7,8]
print(lst)
print(type(lst))
A=np.array(lst)
print(A)
type(A)

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>
[1 2 3 4 5 6 7 8]


numpy.ndarray

In [20]:
tup=((1,2,3,4),(5,6,7,8))
print(tup)
print(type(tup))
B=np.array(tup)
print(B)
type(B)

((1, 2, 3, 4), (5, 6, 7, 8))
<class 'tuple'>
[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [21]:
lst=[1,2,3,4,5,6,7,8]
print(lst)
print(type(lst))
A=np.asarray(lst)
print(A)
type(A)

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>
[1 2 3 4 5 6 7 8]


numpy.ndarray

In [22]:
tup=((1,2,3,4),(5,6,7,8))
print(tup)
print(type(tup))
B=np.asarray(tup)
print(B)
type(B)

((1, 2, 3, 4), (5, 6, 7, 8))
<class 'tuple'>
[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [24]:
fah=np.array([0,12,45.21,34,99.91])
type(fah[0])

numpy.float64

In [26]:
centi = ((fah-32)*(5/9))
centi

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [55]:
arr = np.array([1,2,3], dtype='int64')
arr

array([1, 2, 3], dtype=int64)

In [56]:
print("Size of the array:",np.size(arr))

Size of the array: 3


In [57]:
print("Length of one array element in bytes:",arr.itemsize)

Length of one array element in bytes: 8


In [58]:
print("Length of one array element in bytes:",arr.itemsize*arr.size)

Length of one array element in bytes: 24


## Exercise 6: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [67]:
a = np.array([10, 10, 20, 20, 30, 30])
a

array([10, 10, 20, 20, 30, 30])

In [84]:
b = set(a)
print(b)
c=np.array(list(b))
print(c)
print("Type:",type(c))

{10, 20, 30}
[10 20 30]
Type: <class 'numpy.ndarray'>


In [119]:
a=np.array([[1,1],[2,3]])
b = set((a[0])).union((a[1]))
c = np.array(list(b))
print(c)
print("Type:", type(c))

[1 2 3]
Type: <class 'numpy.ndarray'>


In [125]:
##Alternate Solution
a=np.array([[1,1],[2,3]])
b=set(a.flatten())
c = np.array(list(b))
print(c)
print("Type:", type(c))

[1 2 3]
Type: <class 'numpy.ndarray'>


## Exercise 7: Change the dimension of an array


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [126]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [137]:
a= np.linspace(2.5,6.5,30,endpoint=True) 
print(a)
'''endpoint is optional as default is True'''


[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


'endpoint is optional as default is True'

## Exercise 9: Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


In [172]:
a = np.array([10,20,30])
b = np.array([40,50,60])
##((np.append(a,b,axis=1))
np.stack((a,b),axis=0)


array([[10, 20, 30],
       [40, 50, 60]])

## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [247]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [248]:
for i in range(np.size(a[0])):
    s = 0
    for j in range(np.size(a[i])):
        a[i,j]+=s
        s+=1


In [249]:
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## Exercise 11: Sum of all the multiples of 3 or 5 below 100

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [262]:
a = np.arange(100)
sum=0
for i in a:
    if i%3 ==0 or i%5==0:
        sum+=i
print("Sum is", sum)

Sum is 2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [273]:
a=np.arange(4)
b=np.arange(8).reshape(2,4)
print(a)
print(b)

[0 1 2 3]
[[0 1 2 3]
 [4 5 6 7]]


In [277]:
for i, j in np.nditer([a,b]):
    print(i,':',j)
    

0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [300]:
a = np.array([[0.42436315, 0.48558583, 0.32924763],[0.7439979 , 0.58220701, 0.38213418], [0.5097581 , 0.34528799, 0.1563123 ]])
a

array([[0.42436315, 0.48558583, 0.32924763],
       [0.7439979 , 0.58220701, 0.38213418],
       [0.5097581 , 0.34528799, 0.1563123 ]])

In [304]:
for i in np.nditer(a, op_flags = ["readwrite"]):
    if i > 0.5:
        i[...] = 0.5
a      

array([[0.42436315, 0.48558583, 0.32924763],
       [0.5       , 0.5       , 0.38213418],
       [0.5       , 0.34528799, 0.1563123 ]])

In [339]:
##Alternate solution
a = np.array([[0.42436315, 0.48558583, 0.32924763],[0.7439979 , 0.58220701, 0.38213418], [0.5097581 , 0.34528799, 0.1563123 ]])
print("Before modifying")
print(a)
print("After modifying")
for i in range(np.size(a[0])):
    for j in range(0,np.size(a[i])):
        if (a[i,j])  > 0.5:
            (a[i,j])  = 0.5

print(a)

Before modifying
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
After modifying
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


In [340]:
a=[]
a

[]

In [341]:
a.append(np.array([[10, 20, 30],[40,50,60]]))
a

[array([[10, 20, 30],
        [40, 50, 60]])]

## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [369]:
a = np.array(([1,2,3]))
b = np.array([2,3,4])
print(a)
print(b)
np.stack((a,b),axis=0)

[1 2 3]
[2 3 4]


array([[1, 2, 3],
       [2, 3, 4]])

In [372]:
a=np.array([[1],[2],[3]])
b=np.array([[2],[3],[4]])
print(a)
print(b)
c = np.append(a,b,axis=0)
print(c)

[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
